### ISSUE TITLE
Formally verified contract examples

### ISSUE THREAD

**Issue by cwgoes** [heliaxdev/juvix#139]
We should pick examples with the following properties:
- Implement a system one would have reason to deploy to a distributed ledger
- Are complex or intricate enough to merit non-trivial property verification
- Can be polished into a usable prototype which language users can deploy

Candidate examples:
- Fungible token contract with proofs about constant supply, ownership, fungibility
- Non-fungible token contract with proofs about uniqueness, ownership, transferability
- Uniswap exchange contract with proofs of price slippage, fairness
- [Liberalism radicalism](https://arxiv.org/abs/1809.06421) implementation which plugs into a funder and stakeholder set
- [Wyvern-esque](https://github.com/wyvernprotocol/wyvern-v3) counterfactual decentralised exchange

**Comment by cwgoes** [comment]
- User wallet contract which has a custom validation function for operations. [Reference](https://ethereum-magicians.org/t/erc-1077-and-erc-1078-the-magic-of-executable-signed-messages-to-login-and-do-actions/351/9?u=cwgoes).

**Comment by thealmarty** [comment]
> We should pick examples with the following properties:
> 
>     * Implement a system one would have reason to deploy to a distributed ledger
> 
>     * Are complex or intricate enough to merit non-trivial property verification
> 
>     * Can be polished into a usable prototype which language users can deploy
> 
> 
> Candidate examples:
> 
>     * Fungible token contract with proofs about constant supply, ownership, fungibility

WIP in Idris [here](https://github.com/cryptiumlabs/juvix/tree/develop/experimental/examples/token) - will continue working on it.

**Comment by cwgoes** [comment]
> WIP in Idris [here](https://github.com/cryptiumlabs/juvix/tree/develop/experimental/examples/token) - will continue working on it.

Fantastic - I think we can already figure out many of the tricky questions just by writing prototypes in Idris or Agda - in particular, we can start to write a "fake stdlib" with the data structures we expect to want/need and any properties they will need proofs of (e.g. map behaviour for a token), and use this as a model for the stdlib Juvix will have.

**Comment by cwgoes** [comment]
More ideas for examples:

- Dominant assurance contracts for public-good funding ([paper](https://mason.gmu.edu/~atabarro/PrivateProvision.pdf), [blog post 1](https://www.cato-unbound.org/2017/06/07/alex-tabarrok/making-markets-work-better-dominant-assurance-contracts-some-other-helpful), [blog post 2](https://marginalrevolution.com/marginalrevolution/2013/08/a-test-of-dominant-assurance-contracts.html))

**Comment by cwgoes** [comment]
For the contracts with interesting / specific game-theoretic properties (e.g. dominant assurance properties), we should verify the game-theoretic properties by creating "agents" (just in code - who can interact with the contract) who maximise their own utility functions and prove that the agents will take a certain action when they do this.

**Comment by cwgoes** [comment]
@mariari & @andy-morris to try the monoid-indexed tree proof structure.

**Comment by thealmarty** [comment]
[This paper](https://dl.acm.org/doi/10.1145/2993600.2993611) uses an effect defined in F* to detect vulnerable patterns. I shall experiment with that in various languages. This, along with written proofs, should make pretty solid contract!

**Comment by cwgoes** [comment]
> [This paper](https://dl.acm.org/doi/10.1145/2993600.2993611) uses an effect defined in F* to detect vulnerable patterns. I shall experiment with that in various languages. This, along with written proofs, should make pretty solid contract!

That's an interesting paper, although our task should be somewhat easier since we don't need to start with Solidity code and attempt to type-check it - rather we can enforce whatever types we want at compile-time (including with refinement types, in the future).

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/heliaxdev/juvix/issues/790.
