### ISSUE TITLE
Missing identity.tz contract in Juvix docs

### ISSUE THREAD

**Issue by sean-magin** [heliaxdev/juvix#662]
On https://juvix.org/docs/index the compiled contract `identity.tz` is blank:

<img width="1011" alt="Screen Shot 2021-02-01 at 10 46 25 PM" src="https://user-images.githubusercontent.com/14209806/106442140-cf19ef00-64df-11eb-85dd-16d7cffc3ba6.png">

**Comment by sean-magin** [comment]
Looks like an S is needed here "Interested in being a part of Juvix'**s**

<img width="615" alt="Screen Shot 2021-02-01 at 10 55 20 PM" src="https://user-images.githubusercontent.com/14209806/106442825-a0504880-64e0-11eb-838a-f35cd36d1f03.png">

**Comment by sean-magin** [comment]
Last thing:

<img width="440" alt="Screen Shot 2021-02-01 at 10 58 02 PM" src="https://user-images.githubusercontent.com/14209806/106443095-fae9a480-64e0-11eb-810b-b53451d52e71.png">

As a non-contributor I wasn't able to add the bug tag

**Comment by Asamartino** [comment]
@sean-magin thank you very much for your comments. Will fix it asap.

**Comment by Asamartino** [comment]
@sean-magin thank you for your help. These issues have been fixed.

**Comment by sean-magin** [comment]
Awesome, no worries :)
