### ISSUE TITLE
UnknownSymbol on `+`

### ISSUE THREAD

**Issue by fdedden** [heliaxdev/juvix#674]
When compiling the example provided on the website (https://juvix.org/docs/example/), an error is thrown when encountering the `+` symbol.

```
PipeLine (ContextErr (InfixErr (UnknownSymbol ("+" :| []))))
```

The error is thrown during the contextualisation at:
https://github.com/heliaxdev/juvix/blob/baa699f53854addb99561499bc1e01b2bb811252/library/Translate/src/Juvix/FrontendContextualise/InfixPrecedence/Transform.hs#L56

**Comment by fdedden** [comment]
I will take a look and see if I can find the source of the problem.

**Comment by mariari** [comment]
> I will take a look and see if I can find the source of the problem.

The issue is not with the codebase here but with the example. There is no `+` it can find (as we don't give it one!). So we have to let it know by making a `+` ourselves! 

It just happens to trip up around here during infix resolution as it becomes ambigious what is meant

**Comment by fdedden** [comment]
Ah OK, that makes sense. Adding `open Prelude.Michelson.Alias` solves it, but creates new problems regarding `==`. Are there any plans to add a definition?

There are some other problems with the example, but these should be covered in a separate issue.

**Comment by fdedden** [comment]
Closing this issue, as nothing had to be changed for the particular problem. See #677 for other changes.
