### ISSUE TITLE
Invalid option `-fllvm' with `make build-prod`

### ISSUE THREAD

**Issue by fdedden** [heliaxdev/juvix#679]
When I try to build the optimised compiler, I am greeted with a error from stack:
```sh
stack build --jobs 4 --ghc-options "-O3 -fllvm" --flag juvix:incomplete-error
Invalid option `-fllvm'

Usage: stack build [TARGET] [--dry-run] [--pedantic] [--fast]
....
```

`-fllvm` is treated as an option to stack, and not as part of the `--ghc-options` flag. This is a known issue https://github.com/commercialhaskell/stack/issues/3315, that apparently was fixed. I am running more recent version of stack (2.5.1), but it still comes up as a problem.

A solution to this is by using multiple `--ghc-options` flags:
```sh
stack build --jobs 4 --ghc-options "-O3" --ghc-options "-fllvm" --flag juvix:incomplete-error
```

**Comment by cwgoes** [comment]
> A solution to this is by using multiple `--ghc-options` flags:

Yes, this is what is / was intended.
