### ISSUE TITLE
Explicit pipeline - Feedback

### ISSUE THREAD

**Issue by fdedden** [heliaxdev/juvix#692]
I think that understanding the code as a newcomer is quite difficult. One reason is a lack of comments, but more importantly I think that the whole structure of the code could be more self-explanatory. There are a whole lot of steps the code goes through: parsing, contextToCore, annotation, typechecking etc. Each of these functions rely on the previous ones, e.g. `typecheck` relies on `parse` (which makes sense from the perspective of `typecheck`). The big downside to this is that the pipeline is very implicit: there is no way to instantaneously see where a certain action is done, nor is it easy to add a phase somewhere in-between. Propagating errors or warnings is more difficult as well.

Having an explicitly programmed pipeline, where every phase of the compiler is called, would help greatly with making the code easier to read for newcomers, and ourselves as well. We could achieve this with arrows or monads, or even regular functions (but that would complicate error passing).

A very rough prototype:
```haskell
{-# LANGUAGE Arrows #-}
{-# LANGUAGE FlexibleInstances #-}

module Pipeline where

import Control.Arrow
import Data.Either

type Input = String

data AST       = ...
data LLVM      = ...
data Michelson = ...

-- | The monad instance for Either doesn't have a `fail` by default.
instance MonadFail Feedback where
  fail s = Left s

type Feedback = Either String -- Could be something more specialised to leave
                              -- room for information.

type Pipeline = Kleisli Feedback

-- | 'Inject' a feedback function into the pipeline.
feedback :: (a -> Feedback b) -> Pipeline a b
feedback = Kleisli

-- | Do a full compile, from src code to the target.
-- Arrow might be overkill, but allows is to write loops
-- as well (possibly for recursive optimisations?)
compile :: Pipeline Input (LLVM, Michelson)
compile =  feedback parse
       >>> typecheck
       >>> arr optimisation1
       >>> arr optimisation2
       >>> (generate_llvm &&& generate_michelson)

-----------------------------------------------------
-- | These would all be defined in other files
-----------------------------------------------------
-- | We can use regular functions.
parse :: Input -> Feedback AST
parse "correct" = return AST
parse _         = fail "Parsing error."

-- | Or ones defined in arrows.
typecheck :: Pipeline AST AST
typecheck = ...

-- | Or without feedback altogether, if we want.
optimisation1 :: AST -> AST
optimisation1 = ...

optimisation2 :: AST -> AST
optimisation2 = ...

generate_llvm :: Pipeline AST LLVM
generate_llvm = ...

generate_michelson :: Pipeline AST Michelson
generate_michelson = ...
```

Note that we define the pipeline using a Kleisli arrow, and a possibly custom `Feedback` type to keep track of errors, warnings and information. The `compile` function explicitly defines the full pipeline. Here both LLVM and Michelson is created, but this could be different depending on the outcome of #683.

**Comment by cwgoes** [comment]
Not sure about the exact types, but broadly I think this makes sense. Also, we should move all substantive logic out of `app`; the Juvix library itself should expose all the pipeline components, `app/Compile.hs` should just chain them together with the CLI/REPL.

**Comment by fdedden** [comment]
That was exactly my plan. `app/` should really not be anything more than just the bare code needed for the userspace tools.

Type-wise I agree, the code shown is really nothing more then a very rough prototype to convey the idea.

**Comment by fdedden** [comment]
The approach taken in the code is by using a custom Feedback monad instead of an arrow. Although a monad has a less rigid structure compared to an arrow, it allows us to more easily implement a REPL later on.
