### ISSUE TITLE
Arithmetic underflow in toLambda

### ISSUE THREAD

**Issue by andreaslyn** [heliaxdev/juvix#702]
While playing around with Juvix today I stumbled across a `juvix: arithmetic underflow` error message. For example the following program:
```
mod ArithUnderflow where

open Prelude
open Michelson

sig make-pair : list operation -> int -> pair (list operation) int
let make-pair = %Michelson.pair

sig nil : list operation
let nil = %Michelson.nil

-- Inlining this function is problematic:
sig int-id : int -> int
let int-id x = x

sig main : pair int int -> pair (list operation) int
let main = \ps -> make-pair nil (int-id 10)
```
It seems that the error is happening when inlining global functions of arity 1, such as `int-id` in the above example. There is a simple fix here: https://github.com/heliaxdev/juvix/compare/develop...andreaslyn:andreaslyn/arity1-inline-fix

**Comment by andy-morris** [comment]
Oh, nice catch, thanks so much!
