### ISSUE TITLE
Update style guide

### ISSUE THREAD

**Issue by fdedden** [heliaxdev/juvix#735]
The style guide currently leaves to much room for interpretation, we need to clearify the following:

- [x] Explicit exports.
- [x] Folder names as nouns.
- [x] Folder names directly under `library/` shouldn't start with a capital.
- [x] Module names should not contain prefixes, that is what folders are for.
- [x] Use American English for folders, modules, functions and comments.
- [x] Have argument comments use `-- |` on the line before, instead of `-- ^` on the same line.
- [x] Prefix unused pattern match variables with `_` to avoid large amounts of `-Wunused-matches` warnings, while still keeping the code self-documenting.

See https://github.com/heliaxdev/juvix/issues/734 for more details on folder naming.

**Comment by cyberglot** [comment]
@fdedden should we move all we decided from #734 here?

**Comment by fdedden** [comment]
> @fdedden should we move all we decided from #734 here?

No, I think it is OK. We can leave your issue for actually changing the names of folders. Or do you think these could use their own issues per folder?
