### ISSUE TITLE
LLVM backend

### ISSUE THREAD

**Issue by cwgoes** [heliaxdev/juvix#97]
To output performant code, Juvix must compile to a low-level backend. In the future, we will likely want to support several (Michelson, WASM, LLVM, CUDA, etc.) - but we should pick one to work on first to better understand the abstractions necessary and preferable compiler structure.

I think the best first choice backend at the moment is [LLVM](http://llvm.org/):
- It can target standard computer hardware (x86/AMD64)
- It has a [built-in low-level intermediate form](http://llvm.org/docs/LangRef.html#introduction) and a [variety of optimisation passes](https://llvm.org/docs/Vectorizers.html)
- It supports concurrency (we may want to utilise an existing threading library)
- It has existing, up-to-date [Haskell bindings](https://github.com/llvm-hs/llvm-hs/)

[This well-documented project](http://www.stephendiehl.com/llvm/) may be a helpful reference.

**Comment by cwgoes** [comment]
[A helpful presentation on LLVM IR](https://llvm.org/devmtg/2017-06/1-Davis-Chisnall-LLVM-2017.pdf).

**Comment by cwgoes** [comment]
I expect that the primary CPU optimisation concern will be memory usage, and minimising jumps which are dependent on memory values in a way which may be hard for the processor to pipeline.

Relevant background:
- Summary of [various latencies on modern CPUs](https://gist.github.com/jboner/2841832)).
- Larger summary of [HPC latencies](https://gist.github.com/understeer/4d8ea07c18752989f6989deeb769b778), including GPUs

We might want to experiment with "unrolling" the basic interaction net evaluator case switch by some degree `k`, such that intermediate allocations can be optimised away at compile-time - code size will be `c ^ k` with `c` the number of branches, but that's still fine for a few levels of unrolling.

This transformation is trivially semantics-preserving in the single-thread case and no additional bookkeeping is necessary. In the multi-thread case, if two threads start reduction less than `k` hops from each other (hop = wire between nodes), they may reduce overlapping primary pairs, which could be problematic. We could either attempt to eliminate this possibility at compile time, which will require a fair bit of knowledge about where parallel reduction will occur (but perhaps possible, especially with explicit annotations), or reduce optimistically in parallel, insert synchronisation points where necessary, and revert conflicting changes in a semantics-preserving way - an approach which is more complicated  to reason about, but doesn't require compile-time knowledge of "distance" between threads rewriting the graph in parallel.

**Comment by cwgoes** [comment]
Resources for optimization (outside of the LLVM library itself):

- [Grin](https://github.com/grin-compiler/grin) has a number of simple optimization passes. Some may be suitable specifically for a model of a lazy functional graph evaluator but I expect many are helpful here.
- [MLton](http://mlton.org/CompilerOverview) is a whole-program-optimizing ML compiler.
- [Slide deck on functional language compilation](https://xavierleroy.org/talks/compilation-agay.pdf) from INRIA.
- [Intel Haskell research compiler](https://github.com/IntelLabs/flrc), which has some optimization passes.

Likely there will be at least two levels of optimization: one at the core level (prior to any backend choice), which transforms core terms to core terms, and a backend-specific / machine-specific level which can make decisions based on more granular execution costs.

Another (far future) technique is Markov-chain Monte Carlo search for instruction sequences - https://github.com/cryptiumlabs/juvix/issues/11.

**Comment by cwgoes** [comment]
Further discussions between @mariari @andy-morris and myself:

- Implement the basic rewriting algorithm from the Haskell/Rust in LLVM IR directly
- Represent nodes, addresses as integers of some bit length (maybe `64`)
- Node size, port pointers, node type, etc. must be encoded into integer
- Some nodes will require multiple integers
- Since this is in memory matching specific powers of two may not matter, we should check
- Need to be careful about atomic rewiring in the parallel execution case, use pointers cleverly
- Moderate optimisation is worthwhile but probably not extreme optmisation
- Instead work on making the bespoke path work well & be chosen when suitable

**Comment by cwgoes** [comment]
- Constant-size ports with pointer indirections where the # of ports is above some constant
- Same technique for variable node sizes
- Start with sequential reduction
- For parallel reduction, avoid scanning all nodes, instead branch threads with signal bit or `par`
- Think about how best to deal with case when two threads rewrite same primary pair, try to avoid at compile time by instructing threads to stop at some point (e.g. where they were originally forked)
- Look up precedent for variable sized arrays in LLVM
- Pack vs unpacked space concerns, array vs vector space / time concerns or differences

**Comment by mariari** [comment]
Using sum types requires a lot of `GetElementPointer`, this [article](http://llvm.org/docs/GetElementPtr.html) on it can be quite helpful

**Comment by cwgoes** [comment]
[Another helpful resource from Stephen Diehl](http://dev.stephendiehl.com/numpile/).

**Comment by cwgoes** [comment]
Should this issue have been closed? Maybe we should open a new one which tracks the plan for the LLVM backend.
